### ISSUE TITLE
Droppin' Buckets

### ISSUE THREAD

**Issue by imjakedaniels** [imjakedaniels/raptors_animation#18]
**WHAT IS IT?**
A nice Raptors-centric animation of play-by-play basketball games by the Raptors. Can be posted after every game.

**WHY AM I DOING IT?**
To earn engagement on Reddit. Potentially expand into content for a blog for contribution. Potentially become a patreon biz.

**WHEN IS IT DONE?**
When I post the raptors charts to various social media accounts & reddit.

**TASKS**
- [x] Add segment_geom to signify score disparity #23 
- [ ] [Create accounts to post (via Hootsuite)](https://github.com/users/imjakedaniels/projects/1#card-37931819) #22 
- [ ] [Explore team image consistency](https://github.com/users/imjakedaniels/projects/1#card-37930417) #20 
- [ ] [Build conditional width arg to accomodate players-per-game](https://github.com/users/imjakedaniels/projects/1#card-37931490) #21 
- [ ] [Free throw indicator](https://github.com/users/imjakedaniels/projects/1#card-37930417) #14 
- [ ] Schedule the script

**FUTURE NOTES**
- Two-team version script 
- Scale to display all games played that day in a two-team version
- Patreon
- Blog Collaboration
