### ISSUE TITLE
Free Throw Indicator

### ISSUE THREAD

**Issue by imjakedaniels** [imjakedaniels/raptors_animation#19]
**WHAT IS IT?**
Creative way to distinguish when baskets are free throws in my chart.

**WHY AM I DOING IT?**
Easier to consume the graphic at a glance.

**WHEN IS IT DONE?**
When I've merged a PR with a satisfactory version to the repo.

**TASKS**
- [x] Try greyscale with {magick} pre-processing
- [x] Retry size differences
- [x] Can diff images be on the same layer?
- [ ] Remove shadow from base image

**Comment by imjakedaniels** [comment]
https://www.reddit.com/r/torontoraptors/comments/i64asa/droppin_buckets_raptors_trail_early_and_never/g0uv23b/

**Comment by imjakedaniels** [comment]
![grey_fail](https://user-images.githubusercontent.com/34351878/89725278-c090c600-d9db-11ea-8b9c-001facd21a84.PNG)

GUHHHHH

**Comment by imjakedaniels** [comment]
Size does the same issue. New image layers are ontop of the others. Look into if I can resolve that.

**Comment by imjakedaniels** [comment]
SIZE WORKING
![size_win](https://user-images.githubusercontent.com/34351878/89725476-f171fa80-d9dd-11ea-951b-b57a7dd26ea5.PNG)
Don't mind how it looks. I can test this at least.

**Comment by imjakedaniels** [comment]
Source:
https://guangchuangyu.github.io/pkgdocs/ggimage.html

```r
d$size=seq(.05, .15, length.out=10)

ggplot(d, aes(x, y)) + 
geom_image(aes(image=image, size=I(size)))
`

**Comment by imjakedaniels** [comment]
It doesn't appear other settings have this flexibility.

**Comment by imjakedaniels** [comment]
The `I` is what makes this work. Learned something new. Think this will work for greyscale too (EDIT: it doesn't... iunno why but it doesn't lol)

**Comment by imjakedaniels** [comment]
I have a solution rn but it will need feedback.

**Comment by imjakedaniels** [comment]
![size_upgrade](https://user-images.githubusercontent.com/34351878/89738724-d12b5580-da48-11ea-88e5-f17e3c28c905.PNG)

I need to remove that shadow tbh.
