### ISSUE TITLE
Create Droppin Buckets accounts to post (via Hootsuite)

### ISSUE THREAD

**Issue by imjakedaniels** [imjakedaniels/raptors_animation#22]
**WHAT IS IT?**
Creating the Droppin Buckets Brand pages on Twitter, Instagram, Facebook.

**WHY AM I DOING IT?**
To develop and expand my product's reach.

**WHEN IS IT DONE?**
When I have created the various social media accounts and plugged them into Hootsuite

**TASKS**
- [ ] Create Email
- [ ] Create Profile Picture
- [ ] Create Instagram, Twitter
- [ ] Add accounts to Hootsuite

**FUTURE NOTES**
- I can only have 10 accounts on Hootsuite Premium. I may want to make the droppin buckets a free account since I never will need the scheduling feature and build API request into the script. 
- If instagram does well, I'd look to expand my product into multiple teams and would need one big account that posts all teams, or many small accounts (future investment based on success)
- Can I auto post to Reddit via API directly to r/Raptors as well? Would be great to explore.
